/*
 *  Copyright 2014 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets.arm; 1, 0, 0,569; 10-10-2014 10:02:13; /db/ztree/library/trees/xdctargets/xdctargets-h38x/src/ xlibrary

 */

