/*
 *  Copyright 2014 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets; 1, 0, 3,737; 10-10-2014 10:02:19; /db/ztree/library/trees/xdctargets/xdctargets-h38x/src/ xlibrary

 */

