// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builder.proto

package cc.arduino.builder;

public final class BuilderProto {
  private BuilderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BuildParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BuildParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbuilder.proto\022\005proto\"\307\002\n\013BuildParams\022\027" +
      "\n\017hardwareFolders\030\001 \001(\t\022\024\n\014toolsFolders\030" +
      "\002 \001(\t\022\037\n\027builtInLibrariesFolders\030\003 \001(\t\022\035" +
      "\n\025otherLibrariesFolders\030\004 \001(\t\022\026\n\016sketchL" +
      "ocation\030\005 \001(\t\022\014\n\004fQBN\030\006 \001(\t\022\031\n\021arduinoAP" +
      "IVersion\030\007 \001(\t\022\035\n\025customBuildProperties\030" +
      "\010 \001(\t\022\026\n\016buildCachePath\030\t \001(\t\022\021\n\tbuildPa" +
      "th\030\n \001(\t\022\025\n\rwarningsLevel\030\013 \001(\t\022\026\n\016codeC" +
      "ompleteAt\030\014 \001(\t\022\017\n\007verbose\030\r \001(\010\"\030\n\010Resp" +
      "onse\022\014\n\004line\030\001 \001(\t2r\n\007Builder\0220\n\005Build\022\022",
      ".proto.BuildParams\032\017.proto.Response\"\0000\001\022" +
      "5\n\014Autocomplete\022\022.proto.BuildParams\032\017.pr" +
      "oto.Response\"\000B$\n\022cc.arduino.builderB\014Bu" +
      "ilderProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_BuildParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_BuildParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BuildParams_descriptor,
        new java.lang.String[] { "HardwareFolders", "ToolsFolders", "BuiltInLibrariesFolders", "OtherLibrariesFolders", "SketchLocation", "FQBN", "ArduinoAPIVersion", "CustomBuildProperties", "BuildCachePath", "BuildPath", "WarningsLevel", "CodeCompleteAt", "Verbose", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new java.lang.String[] { "Line", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
