// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builder.proto

package cc.arduino.builder;

public interface BuildParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BuildParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hardwareFolders = 1;</code>
   */
  java.lang.String getHardwareFolders();
  /**
   * <code>optional string hardwareFolders = 1;</code>
   */
  com.google.protobuf.ByteString
      getHardwareFoldersBytes();

  /**
   * <code>optional string toolsFolders = 2;</code>
   */
  java.lang.String getToolsFolders();
  /**
   * <code>optional string toolsFolders = 2;</code>
   */
  com.google.protobuf.ByteString
      getToolsFoldersBytes();

  /**
   * <code>optional string builtInLibrariesFolders = 3;</code>
   */
  java.lang.String getBuiltInLibrariesFolders();
  /**
   * <code>optional string builtInLibrariesFolders = 3;</code>
   */
  com.google.protobuf.ByteString
      getBuiltInLibrariesFoldersBytes();

  /**
   * <code>optional string otherLibrariesFolders = 4;</code>
   */
  java.lang.String getOtherLibrariesFolders();
  /**
   * <code>optional string otherLibrariesFolders = 4;</code>
   */
  com.google.protobuf.ByteString
      getOtherLibrariesFoldersBytes();

  /**
   * <code>optional string sketchLocation = 5;</code>
   */
  java.lang.String getSketchLocation();
  /**
   * <code>optional string sketchLocation = 5;</code>
   */
  com.google.protobuf.ByteString
      getSketchLocationBytes();

  /**
   * <code>optional string fQBN = 6;</code>
   */
  java.lang.String getFQBN();
  /**
   * <code>optional string fQBN = 6;</code>
   */
  com.google.protobuf.ByteString
      getFQBNBytes();

  /**
   * <code>optional string arduinoAPIVersion = 7;</code>
   */
  java.lang.String getArduinoAPIVersion();
  /**
   * <code>optional string arduinoAPIVersion = 7;</code>
   */
  com.google.protobuf.ByteString
      getArduinoAPIVersionBytes();

  /**
   * <code>optional string customBuildProperties = 8;</code>
   */
  java.lang.String getCustomBuildProperties();
  /**
   * <code>optional string customBuildProperties = 8;</code>
   */
  com.google.protobuf.ByteString
      getCustomBuildPropertiesBytes();

  /**
   * <code>optional string buildCachePath = 9;</code>
   */
  java.lang.String getBuildCachePath();
  /**
   * <code>optional string buildCachePath = 9;</code>
   */
  com.google.protobuf.ByteString
      getBuildCachePathBytes();

  /**
   * <code>optional string buildPath = 10;</code>
   */
  java.lang.String getBuildPath();
  /**
   * <code>optional string buildPath = 10;</code>
   */
  com.google.protobuf.ByteString
      getBuildPathBytes();

  /**
   * <code>optional string warningsLevel = 11;</code>
   */
  java.lang.String getWarningsLevel();
  /**
   * <code>optional string warningsLevel = 11;</code>
   */
  com.google.protobuf.ByteString
      getWarningsLevelBytes();

  /**
   * <code>optional string codeCompleteAt = 12;</code>
   */
  java.lang.String getCodeCompleteAt();
  /**
   * <code>optional string codeCompleteAt = 12;</code>
   */
  com.google.protobuf.ByteString
      getCodeCompleteAtBytes();

  /**
   * <code>optional bool verbose = 13;</code>
   */
  boolean getVerbose();
}
