// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: builder.proto

package cc.arduino.builder;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string line = 1;</code>
   */
  java.lang.String getLine();
  /**
   * <code>optional string line = 1;</code>
   */
  com.google.protobuf.ByteString
      getLineBytes();
}
