/*
 *  Copyright 2014 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,740; 10-10-2014 10:02:12; /db/ztree/library/trees/xdctargets/xdctargets-h38x/src/ xlibrary

 */

