#Makefile stub for test output simulation for testing the Buildbot make test fesature

all: test

test: success failure arduinotest

success:
	cat arduino-success.test 

failure:
	cat arduino-mixed.test

test3:
	cat arduino1.test

arduinotest:
	cat arduino-success.test





