#Makefile stub for test output simulation for testing the Buildbot make test fesature

all: test

test: test1 test2 test3

test1:
	cat ex1.txt

test2:
	cat ex2.txt

test3:
	cat ex3.txt

arduinotest:
	cat arduino.test





