#Makefile stub for test output simulation for testing the Buildbot make test fesature

all: test

test: test1 test2 arduinotest

test1:
	cat arduino-success.test 

test2:
	cat arduino-mixed.test

test3:
	cat arduino1.test

arduinotest:
	cat arduino-success.test





