/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A65
 */

#ifndef gnu_targets_arm_rtsv7M_Settings__INTERNAL__
#define gnu_targets_arm_rtsv7M_Settings__INTERNAL__

#ifndef gnu_targets_arm_rtsv7M_Settings__internalaccess
#define gnu_targets_arm_rtsv7M_Settings__internalaccess
#endif

#include <gnu/targets/arm/rtsv7M/Settings.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* Module_startup */
#undef gnu_targets_arm_rtsv7M_Settings_Module_startup
#define gnu_targets_arm_rtsv7M_Settings_Module_startup gnu_targets_arm_rtsv7M_Settings_Module_startup__E

/* Instance_init */
#undef gnu_targets_arm_rtsv7M_Settings_Instance_init
#define gnu_targets_arm_rtsv7M_Settings_Instance_init gnu_targets_arm_rtsv7M_Settings_Instance_init__E

/* Instance_finalize */
#undef gnu_targets_arm_rtsv7M_Settings_Instance_finalize
#define gnu_targets_arm_rtsv7M_Settings_Instance_finalize gnu_targets_arm_rtsv7M_Settings_Instance_finalize__E

/* per-module runtime symbols */
#undef Module__MID
#define Module__MID gnu_targets_arm_rtsv7M_Settings_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL gnu_targets_arm_rtsv7M_Settings_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB gnu_targets_arm_rtsv7M_Settings_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK gnu_targets_arm_rtsv7M_Settings_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF gnu_targets_arm_rtsv7M_Settings_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ gnu_targets_arm_rtsv7M_Settings_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 gnu_targets_arm_rtsv7M_Settings_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 gnu_targets_arm_rtsv7M_Settings_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 gnu_targets_arm_rtsv7M_Settings_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 gnu_targets_arm_rtsv7M_Settings_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 gnu_targets_arm_rtsv7M_Settings_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ gnu_targets_arm_rtsv7M_Settings_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS gnu_targets_arm_rtsv7M_Settings_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create gnu_targets_arm_rtsv7M_Settings_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete gnu_targets_arm_rtsv7M_Settings_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter gnu_targets_arm_rtsv7M_Settings_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave gnu_targets_arm_rtsv7M_Settings_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query gnu_targets_arm_rtsv7M_Settings_Module_GateProxy_query


#endif /* gnu_targets_arm_rtsv7M_Settings__INTERNAL____ */
