/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A71
 */

#ifndef ti_sysbios_xdcruntime__
#define ti_sysbios_xdcruntime__


/*
 * ======== module ti.sysbios.xdcruntime.GateThreadSupport ========
 */

typedef struct ti_sysbios_xdcruntime_GateThreadSupport_Fxns__ ti_sysbios_xdcruntime_GateThreadSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_GateThreadSupport_Fxns__* ti_sysbios_xdcruntime_GateThreadSupport_Module;
typedef struct ti_sysbios_xdcruntime_GateThreadSupport_Params ti_sysbios_xdcruntime_GateThreadSupport_Params;
typedef struct ti_sysbios_xdcruntime_GateThreadSupport_Object ti_sysbios_xdcruntime_GateThreadSupport_Object;
typedef struct ti_sysbios_xdcruntime_GateThreadSupport_Struct ti_sysbios_xdcruntime_GateThreadSupport_Struct;
typedef ti_sysbios_xdcruntime_GateThreadSupport_Object* ti_sysbios_xdcruntime_GateThreadSupport_Handle;
typedef struct ti_sysbios_xdcruntime_GateThreadSupport_Object__ ti_sysbios_xdcruntime_GateThreadSupport_Instance_State;
typedef ti_sysbios_xdcruntime_GateThreadSupport_Object* ti_sysbios_xdcruntime_GateThreadSupport_Instance;

/*
 * ======== module ti.sysbios.xdcruntime.GateProcessSupport ========
 */

typedef struct ti_sysbios_xdcruntime_GateProcessSupport_Fxns__ ti_sysbios_xdcruntime_GateProcessSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_GateProcessSupport_Fxns__* ti_sysbios_xdcruntime_GateProcessSupport_Module;
typedef struct ti_sysbios_xdcruntime_GateProcessSupport_Params ti_sysbios_xdcruntime_GateProcessSupport_Params;
typedef struct ti_sysbios_xdcruntime_GateProcessSupport_Object ti_sysbios_xdcruntime_GateProcessSupport_Object;
typedef struct ti_sysbios_xdcruntime_GateProcessSupport_Struct ti_sysbios_xdcruntime_GateProcessSupport_Struct;
typedef ti_sysbios_xdcruntime_GateProcessSupport_Object* ti_sysbios_xdcruntime_GateProcessSupport_Handle;
typedef struct ti_sysbios_xdcruntime_GateProcessSupport_Object__ ti_sysbios_xdcruntime_GateProcessSupport_Instance_State;
typedef ti_sysbios_xdcruntime_GateProcessSupport_Object* ti_sysbios_xdcruntime_GateProcessSupport_Instance;

/*
 * ======== module ti.sysbios.xdcruntime.SemThreadSupport ========
 */

typedef struct ti_sysbios_xdcruntime_SemThreadSupport_Fxns__ ti_sysbios_xdcruntime_SemThreadSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_SemThreadSupport_Fxns__* ti_sysbios_xdcruntime_SemThreadSupport_Module;
typedef struct ti_sysbios_xdcruntime_SemThreadSupport_Params ti_sysbios_xdcruntime_SemThreadSupport_Params;
typedef struct ti_sysbios_xdcruntime_SemThreadSupport_Object ti_sysbios_xdcruntime_SemThreadSupport_Object;
typedef struct ti_sysbios_xdcruntime_SemThreadSupport_Struct ti_sysbios_xdcruntime_SemThreadSupport_Struct;
typedef ti_sysbios_xdcruntime_SemThreadSupport_Object* ti_sysbios_xdcruntime_SemThreadSupport_Handle;
typedef struct ti_sysbios_xdcruntime_SemThreadSupport_Object__ ti_sysbios_xdcruntime_SemThreadSupport_Instance_State;
typedef ti_sysbios_xdcruntime_SemThreadSupport_Object* ti_sysbios_xdcruntime_SemThreadSupport_Instance;

/*
 * ======== module ti.sysbios.xdcruntime.SemProcessSupport ========
 */

typedef struct ti_sysbios_xdcruntime_SemProcessSupport_Fxns__ ti_sysbios_xdcruntime_SemProcessSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_SemProcessSupport_Fxns__* ti_sysbios_xdcruntime_SemProcessSupport_Module;
typedef struct ti_sysbios_xdcruntime_SemProcessSupport_Params ti_sysbios_xdcruntime_SemProcessSupport_Params;
typedef struct ti_sysbios_xdcruntime_SemProcessSupport_Object ti_sysbios_xdcruntime_SemProcessSupport_Object;
typedef struct ti_sysbios_xdcruntime_SemProcessSupport_Struct ti_sysbios_xdcruntime_SemProcessSupport_Struct;
typedef ti_sysbios_xdcruntime_SemProcessSupport_Object* ti_sysbios_xdcruntime_SemProcessSupport_Handle;
typedef struct ti_sysbios_xdcruntime_SemProcessSupport_Object__ ti_sysbios_xdcruntime_SemProcessSupport_Instance_State;
typedef ti_sysbios_xdcruntime_SemProcessSupport_Object* ti_sysbios_xdcruntime_SemProcessSupport_Instance;

/*
 * ======== module ti.sysbios.xdcruntime.ThreadSupport ========
 */

typedef struct ti_sysbios_xdcruntime_ThreadSupport_Fxns__ ti_sysbios_xdcruntime_ThreadSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_ThreadSupport_Fxns__* ti_sysbios_xdcruntime_ThreadSupport_Module;
typedef struct ti_sysbios_xdcruntime_ThreadSupport_Params ti_sysbios_xdcruntime_ThreadSupport_Params;
typedef struct ti_sysbios_xdcruntime_ThreadSupport_Object ti_sysbios_xdcruntime_ThreadSupport_Object;
typedef struct ti_sysbios_xdcruntime_ThreadSupport_Struct ti_sysbios_xdcruntime_ThreadSupport_Struct;
typedef ti_sysbios_xdcruntime_ThreadSupport_Object* ti_sysbios_xdcruntime_ThreadSupport_Handle;
typedef struct ti_sysbios_xdcruntime_ThreadSupport_Object__ ti_sysbios_xdcruntime_ThreadSupport_Instance_State;
typedef ti_sysbios_xdcruntime_ThreadSupport_Object* ti_sysbios_xdcruntime_ThreadSupport_Instance;

/*
 * ======== module ti.sysbios.xdcruntime.CacheSupport ========
 */

typedef struct ti_sysbios_xdcruntime_CacheSupport_Fxns__ ti_sysbios_xdcruntime_CacheSupport_Fxns__;
typedef const ti_sysbios_xdcruntime_CacheSupport_Fxns__* ti_sysbios_xdcruntime_CacheSupport_Module;


#endif /* ti_sysbios_xdcruntime__ */ 
