#Test builder and runner make file
# each test needs make compiole, make upload, make getResult
#this also need to be done for the build for each environment


#Board info
BOARD		?= atmega328
PORT		?= /dev/ttyUSB0
UPLOAD_SPEED 	?= 57600

#Arduino info
#/home/ricklon/projects/Arduino/testing/tests
TARGET_OS	 	?= windows
ARD_SRC_HOME	?= /home/ricklon/projects/Arduino
ARD_HOME	?= $(ARD_SRC_HOME)/build/$(TARGET_OS)/work
SKT_DIR		?= $(ARD_SRC_HOME)/testing/tests

#Toolchain info
AVRDUDE_BIN	?= $(ARD_HOME)/hardware/tools/avr/bin
ARD_BIN		?= $(ARD_HOME)/hardware/tools/avr/bin
AVRDUDE_CONF	?= $(ARD_HOME)/hardware/tools/avr/etc/avrdude.conf
PROGRAMMER = stk500v1
LIB_DIRS =  $(wildcard $(ARD_HOME)/libraries/*) $(wildcard $(ARD_HOME)/libraries/*/utility) 

OUTPUT_DIR ?= OUT


include Makefile.master
